from swmmtoolbox import swmmtoolbox  # Used to extract data from the binary .out file
import pandas as pd  # Used to create data-frames


def process_output(output_file):
    # Preconditions: A binary .out file generated by SWMM has been passed
    # Postconditions: A .csv file containing data from all variables in variableList has been created in ./data/binary_csv

    variableList = ['Rainfall', 'Evaporation_infiltration', 'Runoff', 'Total_lateral_inflow', 'Flow_leaving_outfalls', 'Evaporation_rate', 'Potential_PET']  # Which catalog variables we want to extract
    input_parameter_list = []
    for variable in variableList:
        input_parameter_list.append('system,' + variable + ',' + variable)

    all_dataframe = swmmtoolbox.extract(output_file, *input_parameter_list)

    filename = './data/binary_csv' + output_file[6:-4] + '.csv'  # Make a pretty .csv file name
    with open(filename, 'w') as file:
        pd.DataFrame.to_csv(all_dataframe, file)  # Write the data-frame to a .csv file





